### ISSUE TITLE
Tweak keeps asking for update in cydia

### ISSUE THREAD

**Issue by one2gov** [EthanRDoesMC/EthanRDoesMC.github.io#2]

**Comment by EthanRDoesMC** [comment]
Confirmed. I have absolutely no idea (so far) how to fix it, but I have it too.

**Comment by EthanRDoesMC** [comment]
Should be fixed.

**Comment by EthanRDoesMC** [comment]
Seems to be back. UGH! I'm going to (try to) make a 10.1.1 version of Gandalf, so I'll see if I can fix this once and for all!

**Comment by EthanRDoesMC** [comment]
Should be fixed by the end of the day.

**Comment by EthanRDoesMC** [comment]
Fixed.
