### ISSUE TITLE
Tweak to be taken out

### ISSUE THREAD

**Issue by adradan** [EthanRDoesMC/EthanRDoesMC.github.io#3]
App sync unified now has a working version for iOS 10

**Comment by EthanRDoesMC** [comment]
Updating to block versions equal to or less than 5.8 


Also angelxwind literally contacted me and last year my claim to fame was 50 Twitter followers lol

**Comment by mehulrao** [comment]
Close this issue? @EthanRDoesMC

**Comment by EthanRDoesMC** [comment]
Um yeah.
