### ISSUE TITLE
Gandalf doesn't show up in your repo

### ISSUE THREAD

**Issue by ann0see** [EthanRDoesMC/EthanRDoesMC.github.io#5]
Maybe only issue for me. 
http://i.imgur.com/wPfb6YJ.png 
Already refreshed sources.

**Comment by mehulrao** [comment]
Having the same issue. Ethan is not responding....

**Comment by EthanRDoesMC** [comment]
Hmmm....

**Comment by EthanRDoesMC** [comment]
Sorry, I just woke up. Saturdayyyyyys

**Comment by EthanRDoesMC** [comment]
I bamboozle free gaurantee you I forgot to run update.sh

**Comment by mehulrao** [comment]
Run it, and then the app may work

**Comment by mehulrao** [comment]
As long as you ran build.sh after i fixed the app @EthanRDoesMC

**Comment by EthanRDoesMC** [comment]
Todayll be fun

**Comment by EthanRDoesMC** [comment]
Okay, remove the new repo, then it'll show up.

**Comment by ann0see** [comment]
The new repo isn't there. It's because the package of the old repo directly includes the gandalf.list which will automatically get removed while installing from the new repo. So the new repo gets added and removed directly after installing the new gandalf from the new repo. So include a `sed` and replace it directly in sources.list.

**Comment by ann0see** [comment]
@EthanRDoesMC now there's a 404 at the old repo.
